project:
  type: website
  output-dir: docs
  resources:
  - webr-serviceworker.js
  - webr-worker.js

website:
  title: "Learning R at the DSL"
  search: true
  reader-mode: true
  favicon: "images/colourful_flora.png"
  sidebar:
    search: true
    style: docked
    pinned: true
    collapse-level: 3
    logo: "images/DigitalSkillsLab.png"
    tools:
      - icon: github
        href: https://github.com/andrewmoles2/DSL-R-Pre-Sessional
    contents:
      - section: "ğŸ“š Information"
        contents: 
        - href: index.qmd
          text: ğŸ  Home
        - href: whyR.qmd
          text: ğŸ“Š Why learn R
      - section: "ğŸ’» R workshops"
        contents: 
          - href: install.qmd
            text: ğŸ› ï¸ Install R and RStudio
          #- href: workshop-materials.qmd
          #  text: ğŸ“– Workshop Materials
          - href: using-files.qmd
            text: ğŸ“ Using R files
      - section: "ğŸ“ R workshops materials"
        contents:
          - href: Project_1.qmd
            text: ğŸ’¡ Project 1 - Temperature metric converter
          - href: Project_2.qmd
            text: ğŸŒ¦ï¸ Project 2 - Building a weather application
          - href: Project_3.qmd
            text: âš™ï¸ Project 3 - Building a weather application continued
          - href: Project_4.qmd
            text: âš½ Project 4 - Football data analysis 
          - href: Project_5.qmd
            text: ğŸ“Š Project 5 - Visualising Olympics data
          - href: Project_6.qmd
            text: ğŸ¨ Project 6 - Data generation and artwork
          - href: Project_7.qmd
            text: ğŸ§¹ Project 7 - Joins and transformations   
      - section: "â“ Other information"
        contents: 
          - href: AI.qmd
            text: ğŸ¤– AI
          - href: faq.qmd
            text: â„¹ï¸ FAQ
          - href: example-page.qmd
            text: ğŸ§ª R Testing Ground


format:
  html:
    theme:
    #https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/posts/17-dark-mode/
      light: [spacelab, css/roboto.css]
      dark: [darkly, css/roboto.css]
    css: css/styles.css
    toc: true
    toc-depth: 4
    toc-location: right-body
    code-fold: false
    mainfont: roboto
    grid:
      sidebar-width: 320px
    include-in-header: 
      - progress-bar.html
    lightbox: auto
    #title-block-banner: "#15BC9B"
    #title-block-banner-color: "#000508"

# Set default options for every webpage that may or may not include webR.
webr: 
  show-startup-message: true    # Display status of webR initialization
#  show-header-message: false     # Check to see if COOP&COEP headers are set for speed.
  packages: ['ggplot2', 'dplyr'] # Pre-install dependencies
#  base-url: ''                   # Base URL used for specifying where R WebAssembly binaries should be located
#  home-dir: '/home/rstudio'      # Customize where the working directory is
#  channel-type: 'post-message'   # Specify communication channel
#  service-worker-url: ''         # URL from where to load JavaScript worker scripts when loading webR with the ServiceWorker communication channel.

# Attach webR to every page
filters:
  - webr

